# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bce202dad85f619e4036d1346e977ed020ca39bdf81699fb39323e5745536c3f94ee2a79608880a99b68d462f6abd7c667fae80d0622fca16ff71f4c934e00d

test:
  secret_key_base: 5d4098f560b9b80bc962fa3ace127c5ddc7b97e7037a1db14c59a7fce914c1ca17a38032f346e2710863516e2136bdd1599f9424b894d6eecd41702f9897fbd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
